# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3177711cd555854919cd6256ebaab51462d26762107810b245a88c7e99d881a8990491eec1962e367e79f4b2962ce2b0f1b9da3e0dfe3b3d9624123d73039881

test:
  secret_key_base: a6d85aff401e62f7013dfecb6bdfec180e79269cb61b1b8916ad3c5fd3f939b98006b2563f61cb7cbafc73e3baddd9054572132b1182e214d08d39b19c88c1ec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
